---
- name: Enable prometheus-node-exporter
  ansible.builtin.systemd_service:
    name: prometheus-node-exporter
    enabled: true
    state: started
- name: Restart prometheus-node-exporter
  ansible.builtin.systemd_service:
    name: prometheus-node-exporter
    state: restarted
