---
- name: Install NFS
  ansible.builtin.dnf:
    name: nfs-utils
    state: present
- name: Enable NFS
  ansible.builtin.systemd_service:
    name: nfs-server
    enabled: true
    state: started
- name: Open necessary ports for firewalld
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  loop: "{{ nfs_firewall_ports }}"
- name: Make NFS share directory
  ansible.builtin.file:
    path: "{{ nfs_directory }}"
    state: directory
    mode: "0777"
    owner: root
    group: root
- name: Edit /etc/exports to enable share
  ansible.builtin.template:
    src: templates/exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart NFS
    - Exportfs
