---
- name: Install podman
  ansible.builtin.dnf:
    name: podman
    state: present
- name: Create Prometheus data dir
  ansible.builtin.file:
    path: /opt/prometheus_data
    state: directory
    owner: root
    group: root
    mode: "0775"
- name: Copy Prometheus config
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /opt/prometheus.yml
    owner: root
    group: root
    mode: "0664"
- name: Pull Prometheus image
  containers.podman.podman_image:
    name: docker.io/prom/prometheus
    tag: latest
- name: Run Prometheus container
  containers.podman.podman_container:
    name: prometheus
    image: docker.io/prom/prometheus
    ports: "9090:9090"
    volume:
      - "/opt/prometheus.yml:/etc/prometheus/prometheus.yml"
      #- "/opt/prometheus_data:/prometheus"
    state: started
