---
- name: Install podman
  ansible.builtin.dnf:
    name: podman
    state: present
- name: Enable linger (for podman containers)
  ansible.builtin.command: loginctl enable-linger
  changed_when: false
- name: Copy Prometheus config
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /opt/prometheus.yml
    owner: root
    group: root
    mode: "0664"
- name: Create Prometheus podman volume
  containers.podman.podman_volume:
    name: prometheus-data
    state: present
- name: Pull Prometheus image
  containers.podman.podman_image:
    name: docker.io/prom/prometheus
    tag: latest
- name: Run Prometheus container
  containers.podman.podman_container:
    name: prometheus
    image: docker.io/prom/prometheus
    ports: "9090:9090"
    volume:
      - "/opt/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "prometheus-data:/prometheus"
    state: started
