---
- name: Run Caddy trust
  become: true
  ansible.builtin.command: caddy trust
  changed_when: false
- name: Enable Caddy
  become: true
  ansible.builtin.systemd_service:
    name: caddy
    enabled: true
- name: Restart Caddy
  become: true
  ansible.builtin.systemd_service:
    name: caddy
    state: restarted
