---
- name: Mount NFS share
  ansible.posix.mount:
    src: "{{ item.key }}"
    path: "{{ item.value }}"
    opts: rw,sync,hard
    boot: true
    state: mounted
    fstype: nfs
  loop: "{{ nfs_client_mounts | dict2items }}"
