---
- name: Provision Pi servers
  hosts: home

  roles:
    - all_pis
    - { role: homepi, when: inventory_hostname == "homepi"}
    - { role: uptime_kuma, when: inventory_hostname == "homepi" }
    - { role: mediapi, when: inventory_hostname == "mediapi"}
    - { role: kavita, when: inventory_hostname == "mediapi" }
    - { role: stirling_pdf, when: inventory_hostname == "mediapi" }
