---
- name: Provision Pi servers
  hosts: home

  pre_tasks:
    - name: Update all packages
      become: true
      ansible.builtin.dnf:
        name: "*"
        state: latest
        update_cache: true
      register: packages
      notify: Display updated packages

  roles:
    # There's no rhyme or reason why some things are in all pis -- I should break these out to separate roles
    - role: all_pis
      tags: setup

    - role: rsyslog
      tags: setup

    - role: ca_client
      tags:
        - setup
        - certs

    - role: homepi
      when: inventory_hostname == "homepi"
      tags:
        - homepi
        - container

    - role: mediapi
      when: inventory_hostname == "mediapi"
      tags:
        - mediapi
        - container

    - role: kavita
      when: inventory_hostname == "mediapi"
      tags:
        - mediapi
        - container

    - role: stirling_pdf
      when: inventory_hostname == "mediapi"
      tags:
        - mediapi
        - container

    - role: flyimg
      when: inventory_hostname == "mediapi"
      tags:
        - mediapi
        - container

    - role: air_quality
      when: inventory_hostname == "mediapi"
      tags:
        - mediapi
        - container

    - role: searxng
      when: inventory_hostname == "mediapi"
      tags:
        - mediapi
        - container

    - role: caddy
      tags:
        - homepi
        - mediapi
        - reverse_proxy

  handlers:
    - name: Display updated packages
      ansible.builtin.debug:
        var: packages
      when: packages is defined
