---
- name: Test
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Systemd Test
      ansible.builtin.systemd_service:
        state: stopped
        scope: user
        name: language-server
