---
- name: Test
  hosts: localhost
  connection: local
  gather_facts: false
  vars:


  tasks:
    # - name: Test URI
    #   ansible.builtin.uri:
    #     url: https://matthewbriancohen.art
    #     return_content: true
    #   register: url_output
    # - name: Display
    #   ansible.builtin.debug:
    #     msg: "{{ url_output }}"
    #   when: url_output.status != 200 or "'Cohen' in url_output.content"
    # - name: Register test file info
    #   ansible.builtin.stat:
    #     path: /home/mbc/test_file.txt
    #   register: test_file
    # - name: Display test file info
    #   ansible.builtin.debug:
    #     var: test_file
    # - name: Sort test file
    #   ansible.builtin.command: sort --unique --output=/home/mbc/test_file.txt /home/mbc/test_file.txt
    #   register: test_output
    #   changed_when: false
    # - name: Display Test File Output
    #   ansible.builtin.debug:
    #     var: test_output
    - name: Resgister test string dnf
      ansible.builtin.command: echo kernel
      register: dnf_updates
      notify: Restart
      changed_when: true
    - name: Display DNF
      ansible.builtin.debug:
        var: dnf_updates
  handlers:
    - name: Restart
      ansible.builtin.debug:
        msg: "yes, this hit"
      when: dnf_updates.stdout.find('kernel') != -1
