---
- name: Update all servers to latest packages
  hosts: personal
  gather_facts: true
  become: true

  tasks:
    - name: APT Update
      block:
        - name: Update all packages (with apt)
          ansible.builtin.apt:
            update-cache: true
            upgrade: true
          register: apt_updates
          notify: Display updated apt packages
        - name: Check if reboot is required (apt)
          ansible.builtin.command: needrestart -b
          register: apt_reboot
          changed_when: apt_reboot.rc != 0
          failed_when: false
          notify: Reboot Debian machine
      when: ansible_distribution == "Debian"

    - name: DNF Update
      block:
        - name: Update all packages (with dnf)
          ansible.builtin.dnf:
            name: "*"
            state: latest
            update_cache: true
          register: dnf_updates
          notify: Display updated dnf packages
        - name: Check if reboot is required (dnf)
          ansible.builtin.command: dnf needs-restarting -r
          register: dnf_reboot
          changed_when: dnf_reboot.rc != 0
          failed_when: false
          notify: Reboot AlmaLinux machine
      when: ansible_distribution == "AlmaLinux"

  handlers:
    - name: Display updated apt packages
      ansible.builtin.debug:
        var: apt_updates
      when: apt_updates is defined
    - name: Display updated dnf packages
      ansible.builtin.debug:
        var: dnf_updates
      when: dnf_updates is defined

    - name: Reboot AlmaLinux machine
      ansible.builtin.reboot:
        msg: "Rebooting system..."
        reboot_timeout: 3600
        test_command: uptime
    - name: Reboot Debian machine
      ansible.builtin.reboot:
        msg: "Rebooting system..."
        reboot_timeout: 3600
        test_command: uptime
