---
- name: Update all servers to latest packages
  hosts: personal
  gather_facts: true
  become: true

  tasks:
    - name: Update all packages (with apt)
      ansible.builtin.apt:
        update-cache: true
        upgrade: true
      when: ansible_distribution == "Debian"
      register: apt_updates
      notify:
        - Display updated apt packages
        # - Reboot Debian machine
    - name: Update all packages (with dnf)
      ansible.builtin.dnf:
        name: "*"
        state: latest
        update_cache: true
      when: ansible_distribution == "AlmaLinux"
      register: dnf_updates
      notify:
        - Display updated dnf packages
        # - Reboot AlmaLinux machine

  handlers:
    - name: Display updated apt packages
      ansible.builtin.debug:
        var: apt_updates
      when: apt_updates is defined
    - name: Display updated dnf packages
      ansible.builtin.debug:
        var: dnf_updates
      when: dnf_updates is defined

    - name: Restart AlmaLinux containers
      containers.podman.podman_containers:
        containers:
          - name: url
            image: docker.io/draganczukp/simply-shorten:latest
          - name: listmonk_db
            image: docker.io/library/postgres:13
          - name: listmonk_app
            image: docker.io/listmonk/listmonk:latest

    - name: Reboot AlmaLinux machine
      ansible.builtin.reboot:
        msg: "Rebooting system for kernel updates..."
      when: dnf_updates is defined and "'kernel' in dnf_updates.results | to_json"
      notify: Restart AlmaLinux containers
    - name: Reboot Debian machine
      ansible.builtin.reboot:
        msg: "Rebooting system for kernel updates..."
      when: apt_updates is defined and "'kernel' in apt_updates.stdout | to_json"
