---
- name: Provision Arch Testing box
  hosts: all
  become: true

  vars:
    zfs_key: DDF7DB817396A49B2A2723F7403BD972F75D9D76

  pre_tasks:

    - name: Import key for ZFS - 1
      ansible.builtin.command: 'pacman-key -r "{{ zfs_key }}"'
      changed_when: false

    - name: Import key for ZFS - 2
      ansible.builtin.command: 'pacman-key --lsign-key "{{ zfs_key }}"'
      changed_when: false

    - name: Update packages
      community.general.pacman:
        update_cache: true
        upgrade: true
      register: pacman_updates
      notify: Pacman updates

  tasks:
    - name: Add ZFS repo
      ansible.builtin.blockinfile:
        path: /etc/pacman.conf
        block: |
          [archzfs]
          Server = https://archzfs.com/$repo/$arch
          Server = https://zxcvfdsa.com/archzfs/$repo/$arch


    - name: Install ZFS
      community.general.pacman:
        name: archzfs-linux
        state: present
        update_cache: true
      notify: Reboot machine

  handlers:
    - name: Pacman updates
      ansible.builtin.debug:
        var: pacman_updates
    - name: Reboot machine
      ansible.builtin.reboot:
        msg: rebooting to use ZFS
