---
- name: Restart SMB
  ansible.builtin.systemd_service:
    name: smb
    state: restarted
- name: Apply SELinux context
  ansible.builtin.command: restorecon -irv "{{ smb_directory }}"
  changed_when: false
