---
- name: Restart mariadb
  ansible.builtin.systemd_service:
    name: mariadb
    state: restarted
- name: Restart Semaphore
  ansible.builtin.systemd_service:
    name: semaphore
    state: restarted
- name: Restart SSHD
  ansible.builtin.systemd_service:
    name: sshd
    state: restarted
