---
on:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v6

      - name: Minimum linter
        run: ansible-lint --profile=min

  inventory:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v6

      - name: Install required collections
        run: ansible-galaxy collection install -r requirements.yml
        working-directory: ./HomeLab

      - name: Put vault pass on system
        run: echo "${{ secrets.ANSIBLE_PROXMOX_VAULT_PASSWORD }}" >
          /tmp/vault_password.txt

      - name: Inventory check
        run: ansible-inventory --graph --vault-password-file /tmp/vault_password.txt
        working-directory: ./HomeLab

      - name: Clean up secrets
        if: always()
        run: rm -f /tmp/vault_password.txt
  # build-infra:
  #   runs-on: self-hosted
  #   needs: lint
  #   steps:
  #     - uses: actions/checkout@v6
  #     - name: Apply config
  #       run: ansible
  #       working-directory: ./HomeLab
