---
on:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v6
      - name: Minimum linter
        run: ansible-lint --profile=min
        working-directory: ./HomeLab
  inventory:
    runs-on: self-hosted
    steps:
      - name: Inventory Check
        run: ansible-inventory --graph --vault-password-file group_vars/all/.vault
  # build-infra:
  #   runs-on: self-hosted
  #   needs: lint
  #   steps:
  #     - uses: actions/checkout@v6
  #     - name: Apply config
  #       run: ansible
  #       working-directory: ./HomeLab
