---
- name: Install NSS
  ansible.builtin.dnf:
    name: nss-tools
    state: present
- name: Install Caddy
  ansible.builtin.dnf:
    name: caddy
    state: present
  notify: Enable Caddy
- name: Copy Caddyfile
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: /etc/caddy/Caddyfile
    mode: "0644"
  notify: Restart Caddy
