---
- name: Install NSS
  become: true
  ansible.builtin.dnf:
    name: nss-tools
    state: present

- name: Install Caddy
  become: true
  ansible.builtin.dnf:
    name: caddy
    state: present
  notify:
    - Enable Caddy
    - Run Caddy trust

- name: Copy Caddyfile
  become: true
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: /etc/caddy/Caddyfile
    owner: root
    group: root
    mode: "0644"
  notify: Restart Caddy

- name: Fetch Caddy certs
  become: true
  ansible.builtin.fetch:
    src: /var/lib/caddy/.local/share/caddy/pki/authorities/local/root.crt
    dest: /tmp/cert
  register: cert_location

- name: Display Cert info
  ansible.builtin.debug:
    var: cert_location.dest

- name: Run trust command on localhost
  become: true
  ansible.builtin.command: trust anchor {{ cert_location.dest }}
  changed_when: false
  delegate_to: localhost

- name: Remove Caddy certs
  ansible.builtin.file:
    path: "{{ cert_location.dest }}"
    state: absent
  delegate_to: localhost
