---
- name: Install Smallstep CLI
  become: true
  when: ansible_distribution != "Debian"
  block:
    - name: Create Smallstep repo
      ansible.builtin.template:
        src: smallstep.repo.j2
        dest: /etc/yum.repos.d/smallstep.repo
        mode: "0644"
    - name: Install Smallstep
      ansible.builtin.dnf:
        name: step-cli
        state: present

- name: Tell user to trust Root CA
  ansible.builtin.debug:
    msg: "Make sure you run 'step ca bootstrap --ca-url CA_URL --fingerprint CA_FINGERPRINT' and then 'step certificate install ROOT_CRT' !"
