---
- name: Set up CA server
  hosts: ca
  become: true

  roles:
    - role: rsyslog
      tags: logs

    - role: sshd

    - role: sudo

    - role: prometheus_client
      tags: metrics

    - role: ca
