---
- name: Container Provisioning
  become: true
  hosts: proxmox_all_lxc

  pre_tasks:
    - name: Update all packages
      ansible.builtin.dnf:
        name: "*"
        state: latest
  tasks:
    - name: Install SSHD
      ansible.builtin.dnf:
        name: openssh-server
        state: present
    - name: Copy MBC SSH key
      ansible.posix.authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', '/home/mbc/.ssh/id_ed25519.pub') }}"
    - name: Set timezone to Los Angeles
      community.general.timezone:
        name: America/Los_Angeles
    - name: Check if EPEL is installed
      ansible.builtin.stat:
        path: /etc/yum.repos.d/epel.repo
      register: epel
    - name: Install EPEL repo
      ansible.builtin.dnf:
        name: epel-release
        state: present
    - name: Enable EPEL CRB
      ansible.builtin.command: dnf config-manager --set-enabled crb
      register: crb_output
      changed_when: crb_output.rc != 0
      when: not epel.stat.exists
    - name: Install Prometheus Node Exporter
      ansible.builtin.dnf:
        name: golang-github-prometheus-node-exporter
        state: present
    - name: Enable Prometheus node exporter service
      ansible.builtin.systemd_service:
        name: prometheus-node-exporter
        enabled: true
        state: started
