---
- name: Set up DNS servers
  hosts: dns01,dns02
  become: true

  roles:
    - role: rsyslog
      tags: logs

    - role: prometheus_client

    - role: ca_client

    - role: pihole

    - role: tailscale
      tags: tailscale
