---
- name: Set up Files server
  hosts: files
  become: true

  roles:
    - role: prometheus_client
    - role: freeipa_client
    - role: ca_client
    - role: aide
    - role: opnsense_backups
    - role: nfs
    - role: resilio_sync
    - role: syncthing
    - role: torrent
    - role: caddy
    - role: wazuh_agent
    - role: debug
