---
- name: Set up Files server
  hosts: files
  become: true

  roles:
    - role: nfs
    - role: resilio_sync
    - role: syncthing
    - role: prometheus_client
    - role: freeipa_client
    - role: ca_client
    - role: opnsense_backups
