---
- name: Set up FreeIPA
  hosts: freeipa
  become: true

  roles:
    - role: rsyslog
    - role: freeipa
    - role: prometheus_client
    - role: ca_client
    - role: nfs_client
    - role: freeipa_client
    - role: aide
    - role: wazuh_agent
    - role: debug
