---
- name: Set up FreeIPA
  hosts: freeipa
  become: true

  roles:
    - role: rsyslog
      tags: logs

    - role: freeipa
      tags: auth_server

    - role: prometheus_client
      tags: metrics

    - role: freeipa_client
      tags: auth

    - role: ca_client
      tags: auth

    - role: nfs_client
      tags: files

    - role: aide
      tags: security

    - role: wazuh_agent
      tags: security

    - role: serial
      tags: test

    - role: debug
      tags: test
