---
- name: Install Prometheus and Grafana
  hosts: graphs
  become: true

  roles:
    - role: rsyslog

    - role: prometheus_client

    - role: ca_client

    - role: prometheus

    - role: grafana
