---
- name: Install Prometheus and Grafana
  hosts: graphs
  become: true

  roles:
    - role: rsyslog
      tags: logs

    - role: prometheus_client
      tags: metrics

    - role: ca_client
      tags: auth

    - role: prometheus

    - role: grafana
