---
- name: Install Prometheus and Grafana
  hosts: graphs
  become: true

  roles:
    - role: rsyslog
      tags: logs

    - role: auditd
      tags: audit

    - role: sshd

    - role: sudo

    - role: prometheus_client
      tags: metrics

    - role: freeipa_client
      tags: auth

    - role: ca_client
      tags: auth

    - role: aide
      tags: security

    - role: wazuh_agent
      tags: security

    - role: selinux
      tags: security

    - role: dnf
      tags: proxy,dnf

    - role: serial
      tags: test

    - role: debug
      tags: test

    - role: prometheus
      tags: prometheus

    - role: grafana
      tags: grafana

    - role: caddy
      tags: web
