---
- name: Set up Self-Hosted server
  hosts: hosted
  become: true

  roles:
    - role: rsyslog
      tags: logs

    - role: auditd
      tags: audit

    - role: sshd

    - role: sudo

    - role: prometheus_client
      tags: metrics

    - role: freeipa_client
      tags: auth

    - role: ca_client
      tags: auth

    - role: aide
      tags: security

    - role: wazuh_agent
      tags: security

    - role: selinux
      tags: security

    - role: serial
      tags: test

    - role: debug
      tags: test

    - role: caddy
      tags: web

    - role: mealie
      tags: cooking
