---
- name: Set up logs server
  hosts: logs
  become: true

  roles:
    - role: rsyslog
      tags: logs

    - role: prometheus_client
      tags: metrics

    - role: ca_client
      tags: auth

    - role: loki

    - role: alloy
