---
- name: Set up email server
  hosts: mail
  become: true

  roles:
    - role: rsyslog
      tags: logs

    - role: sshd

    - role: sudo

    - role: prometheus_client
      tags: metrics

    - role: ca_client
      tags: auth
