---
- name: Set up Netbox server
  hosts: netbox
  become: true

  roles:
    - role: rsyslog
    - role: freeipa_client
    - role: ca_client
    - role: prometheus.prometheus.node_exporter # installs prometheus on rhel10, install with ansible-galaxy collection install prometheus.prometheus
    - role: wazuh_agent
    - role: debug
