---
- name: Set up Netboot server
  hosts: netboot
  become: true

  roles:
    - role: rsyslog
    - role: prometheus_client
    - role: ca_client
    - role: freeipa_client
    - role: nfs_client
    - role: wazuh_agent
    - role: pxe
    #- role: netbootxyz
    #- role: caddy
