---
- name: Initial provisioning for new containers
  become: true
  hosts: proxmox_nodes

  # This isn't a great solution, but if I add container ids here manually, this should work
  # Weirdly RHEL based/Arch containers don't have ssh enabled by default, but Debian does
  vars:
    vm_ids:
      - 101
      - 102
      - 103

  pre_tasks:
    - name: Update all packages
      ansible.builtin.package:
        name: "*"
        state: latest

  tasks:
    - name: Install OpenSSH server on container
      ansible.builtin.command: lxc-attach "{{ item }}" -- dnf install -y openssh-server
      loop: "{{ vm_ids }}"
      notify: Restart SSHD
  handlers:
    - name: Restart SSHD
      ansible.builtin.command: lxc-attach "{{ item }}" -- systemctl restart sshd
      loop: "{{ vm_ids }}"
