---
- name: Initial provisioning for new containers
  become: true
  hosts: services

  # This isn't a great solution, but if I add container ids here manually, this should work
  # Weirdly RHEL based/Arch containers don't have ssh enabled by default, but Debian does
  # TO DO: loop over each container in inventory, get proxmox_hostname["ansible_inventory"].proxmox_vmid
  vars:
    vm_ids:
      - 107
      - 110
      - 116
      - 117

  tasks:
    - name: Copy Proxmox SSH key
      ansible.posix.authorized_key:
        user: root
        state: present
        key: "{{ proxmox_pub_key }}"

    - name: Container Provision
      block:
        - name: Install OpenSSH server on container
          ansible.builtin.command: lxc-attach "{{ item }}" -- dnf install -y openssh-server
          loop: "{{ vm_ids }}"
          notify: Restart SSHD
          changed_when: false

        # - name: Create ansible service account on container (RHEL)
        #   ansible.builtin.command: lxc-attach "{{ item }}" -- useradd -m -G wheel -p "{{ vault_container_password }} ansible"
        #   loop: "{{ vm_ids }}"

        # Curl the proxmox public key from github, put it in authorized_keys for ansible user

  handlers:
    - name: Restart SSHD
      ansible.builtin.command: lxc-attach "{{ item }}" -- systemctl restart sshd
      loop: "{{ vm_ids }}"
