---
- name: Provisioning HomeLab Container/VMs
  become: true
  hosts: proxmox_all_lxc, proxmox_all_qemu

  vars:
    rhel_package_list:
      - openssh-server
      - python3-pexpect # for expect module
      - golang-github-prometheus-node-exporter
      - vim
      - lsof
      - iperf3
    debian_package_list:
      - prometheus-node-exporter
      - vim

  pre_tasks:
    - name: Update all packages
      ansible.builtin.package:
        name: "*"
        state: latest
      register: package_updates
      notify: Display updated packages
    - name: Set hostname to be FQDN
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}.{{ domain }}"
        use: systemd
      when: inventory_hostname != "freeipa"
    - name: Make sure ansible service account user exists
      ansible.builtin.user:
        name: ansible
        comment: Ansible Service Account
    - name: Copy Proxmox SSH key
      ansible.posix.authorized_key:
        user: ansible
        state: present
        key: "{{ lookup('file', '/home/mbc/.ssh/proxmox.pub') }}"
    - name: Set Ansible user to NOPASSWD in sudoers
      community.general.sudoers:
        name: 99-ansible
        state: present
        user: ansible
        commands: ALL
        host: ALL
        nopassword: true
    - name: Check for existence of CA SSH key
      local_action:
        module: ansible.builtin.stat
        path: /tmp/ca-cert.pub
      register: ca_cert
    - name: Copy CA SSH key
      ansible.posix.authorized_key:
        user: ansible
        state: present
        key: "{{ lookup('file', '/tmp/ca-cert.pub') }}"
      when: ca_cert.stat.exists
    - name: Remove MBC SSH key from Ansible service account
      ansible.posix.authorized_key:
        user: ansible
        state: absent
        key: "{{ lookup('file', '/home/mbc/.ssh/id_ed25519.pub') }}"
    - name: Alma/RHEL specific tasks
      when: ansible_distribution != "Debian"
      block:
        - name: Check if EPEL is installed
          ansible.builtin.stat:
            path: /etc/yum.repos.d/epel.repo
          register: epel
        - name: Install EPEL repo
          ansible.builtin.dnf:
            name: epel-release
            state: present
        - name: Enable EPEL CRB
          ansible.builtin.command: dnf config-manager --set-enabled crb
          register: crb_output
          changed_when: crb_output.rc != 0
          when: not epel.stat.exists
        - name: Install necessary packages
          ansible.builtin.dnf:
            name: "{{ item }}"
            state: present
          loop: "{{ rhel_package_list }}"
          ignore_errors: true

  roles:
    - role: rsyslog
    - role: ca_client

  tasks:
    - name: Set timezone to Los Angeles
      community.general.timezone:
        name: America/Los_Angeles

    - name: Debian specific tasks
      when: ansible_distribution == "Debian"
      block:
        - name: Install necessary packages
          ansible.builtin.apt:
            name: "{{ item }}"
            state: present
          loop: "{{ debian_package_list }}"

    - name: Install QEMU guest agent
      ansible.builtin.package:
        name: qemu-guest-agent
        state: present
      notify: Enable QEMU guest agent
      when: "'proxmox_all_qemu' in group_names"

  handlers:
    - name: Display updated packages
      ansible.builtin.debug:
        var: package_updates
      when: package_updates is defined
    - name: Enable QEMU guest agent
      ansible.builtin.systemd_service:
        name: qemu-guest-agent
        enabled: true
        state: started
    - name: Enable Prometheus node exporter service
      ansible.builtin.systemd_service:
        name: prometheus-node-exporter
        enabled: true
        state: started
