---
- name: Set up Semaphore server
  hosts: semaphore
  become: true

  roles:
    - role: rsyslog
    - role: freeipa_client
    - role: ca_client
    #- role: prometheus.prometheus.node_exporter # installs prometheus on rhel10, install with ansible-galaxy collection install prometheus.prometheus
    - role: prometheus_client
    - role: semaphore
    - role: caddy
    - role: wazuh_agent
    - role: debug
