---
- name: Test
  hosts: logs
  vars:
    version: "2.14.12"
  tasks:
    - name: Check if AIDE exists
      ansible.builtin.stat:
        path: /sr/sbin/aide
      register: aide
    - name: Debug
      ansible.builtin.debug:
        var: aide
