---
- name: Set up Test server
  hosts: test
  become: true

  roles:
    - role: debug
    - role: rsyslog
    - role: prometheus.prometheus.node_exporter # installs prometheus on rhel10, install with ansible-galaxy collection install prometheus.prometheus
    - role: freeipa_client
    - role: wazuh_agent
