---
- name: Set up Wazuh server
  hosts: wazuh
  become: true

  roles:
    - role: rsyslog
      tags: logs

    - role: auditd
      tags: audit

    - role: sshd

    - role: sudo

    - role: prometheus_client
      tags: metrics

    - role: freeipa_client
      tags: auth

    - role: ca_client
      tags: auth

    - role: selinux
      tags: security

    - role: aide
      tags: security

    - role: wazuh_server
      tags: security

    - role: postfix
      tags: mail

    - role: dnf
      tags: proxy,dnf

    - role: serial
      tags: test

    - role: debug
      tags: test
