---
- name: Set up Wazuh server
  hosts: wazuh
  become: true

  roles:
    - role: rsyslog
    - role: prometheus_client
    - role: freeipa_client
    - role: ca_client
    - role: aide
    - role: wazuh_server
    - role: debug
