---
- name: Enable Fail2Ban
  become: true
  ansible.builtin.systemd_service:
    name: fail2ban
    enabled: true
- name: Restart Fail2Ban
  become: true
  ansible.builtin.systemd_service:
    name: fail2ban
    state: restarted
