---
- ansible.builtin.include_tasks: setup.yml
- ansible.builtin.include_tasks: pihole.yml
- ansible.builtin.include_tasks: prometheus.yml
- ansible.builtin.include_tasks: syncthing.yml

- name: Enable linger (for podman containers)
  ansible.builtin.command: loginctl enable-linger
  changed_when: false
- name: Enable podman auto update systemd timer
  ansible.builtin.systemd_service:
    name: podman-auto-update.timer
    enabled: true
    state: started
    scope: user
