---
- name: Open PiHole ports
  become: true
  ansible.posix.firewalld:
    service: "{{ item }}"
    state: enabled
    permanent: true
    immediate: true
  loop: "{{ all_pis_pihole_ports }}"
- name: Check if ftl firewalld zone exists
  ansible.builtin.command: firewall-cmd --get-zones
  register: ftl_output
  changed_when: false
- name: Create firewalld ftl zone for PiHole
  become: true
  ansible.builtin.command: firewall-cmd --permanent --new-zone ftl
  register: ftl_zone_output
  when: '"ftl" in ftl_output'
  changed_when: ftl_zone_output.rc == 0
- name: Reload firewalld to use ftl zone
  become: true
  ansible.builtin.command: firewall-cmd --reload
  when: ftl_zone_output is defined
  changed_when: false
- name: Open local zone port for PiHole
  become: true
  ansible.posix.firewalld:
    zone: ftl
    port: 4711/tcp
    permanent: true
    immediate: true
    state: enabled
- name: Add Pihole OS Check Disabled environment variable
  become: true
  ansible.builtin.lineinfile:
    path: /etc/environment
    line: PIHOLE_SKIP_OS_CHECK=true
    state: present
