---
- name: Install Syncthing
  become: true
  ansible.builtin.dnf:
    name: syncthing
    state: present
- name: Open Syncthing firewall ports
  become: true
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  loop: "{{ all_pis_syncthing_ports }}"
- name: Set Syncthing to listen on all interfaces
  ansible.builtin.replace:
    path: "{{ ansible_user_dir }}/.local/state/syncthing/config.xml"
    regexp: 127\.0\.0\.1:8384
    replace: 0.0.0.0:8384
    backup: true
- name: Enable Syncthing service
  ansible.builtin.systemd_service:
    name: syncthing
    enabled: true
    state: started
    scope: user
