---
- name: Restart NFS
  become: true
  ansible.builtin.systemd_service:
    name: nfs-server
    state: restarted
- name: Exportfs
  become: true
  ansible.builtin.command: exportfs -av
  changed_when: false
