---
- name: Restart Netbox
  become: true
  become_user: netbox
  ansible.builtin.systemd_service:
    name: netbox-pod
    state: restarted
    scope: user
- name: Restart SSHD
  ansible.builtin.systemd_service:
    name: sshd
    state: restarted
