---
- name: Enable NFS
  become: true
  ansible.builtin.systemd_service:
    name: nfs-server
    enabled: true
- name: Restart NFS
  become: true
  ansible.builtin.systemd_service:
    name: nfs-server
    state: restarted
