---
- name: Configure chrony (RHEL)
  when: ansible_facts["distribution"] == "AlmaLinux"
  block:
    - name: Change chrony config
      ansible.builtin.lineinfile:
        path: /etc/chrony.conf
        regexp: "iburst$"
        line: "server opnsense.localdomain iburst"
      notify: Restart chrony

- name: Configure chrony (Debian)
  when: ansible_facts["distribution"] == "Debian"
  block:
    - name: Ensure sources.d directory exists
      ansible.builtin.file:
        path: /etc/chrony/sources.d
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Add sources file (Deb)
      ansible.builtin.copy:
        src: opnsense.sources
        dest: /etc/chrony/sources.d/
        owner: root
        group: root
        mode: "0644"
      notify: Reload chrony sources
