---
- name: Start Jenkins Systemd unit file
  ansible.builtin.systemd_service:
    name: jenkins
    state: started
    daemon_reload: true
- name: Restart nginx
  ansible.builtin.systemd_service:
    name: nginx
    state: restarted
