---
- name: Enable Rsyslog
  become: true
  ansible.builtin.systemd_service:
    name: rsyslog
    enabled: true
    state: started
- name: Restart Rsyslog
  become: true
  ansible.builtin.systemd_service:
    name: rsyslog
    state: restarted
