---
- name: Get service facts
  ansible.builtin.service_facts:
- name: Install NFS
  ansible.builtin.dnf:
    name: nfs-utils
    state: present
  notify: Enable NFS
- name: Open necessary ports for firewalld
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  loop:
    - nfs
    - nfs3
    - mountd
    - rpc-bind
  when: ansible_facts.services['firewalld'] is defined
- name: Make NFS share directory
  ansible.builtin.file:
    path: "{{ nfs_directory }}"
    owner: "{{ nfs_user }}"
    group: "{{ nfs_group }}"
    mode: "0755"
- name: Edit /etc/exports to enable share
  ansible.builtin.template:
    src: templates/exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: "0644"
  notify: Restart NFS
    
