---
- name: Install podman
  become: true
  ansible.builtin.dnf:
    name: podman
    state: present
- name: Create certs directory
  become: true
  ansible.builtin.file:
    name: /opt/certs
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"
- name: Create hardlink to root cert
  ansible.builtin.file:
    src: /home/almalinux/.step/certs/root_ca.crt
    dest: /opt/certs/root_ca.crt
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0600"
    state: hard
- name: Create Uptime Kuma quadlet file
  containers.podman.podman_container:
    name: uptime-kuma
    image: docker.io/louislam/uptime-kuma:1
    state: quadlet
    quadlet_filename: uptime-kuma
    quadlet_dir: "{{ ansible_user_dir }}/.config/containers/systemd"
    ports:
      - 3001:3001
    volumes:
      - "uptime-kuma:/app/data:z"
      # - "/opt/certs:/opt/certs:z" # needed so uptime-kuma can trust my root-ca - this dir has a hardlink to my root cert
    quadlet_options:
      - "AutoUpdate=registry"
      # - "Environment=NODE_EXTRA_CA_CERTS=/opt/certs/root_ca.crt" # need to pass this variable so uptime kuma uses root ca
      - |
        [Service]
        Restart=always
        [Install]
        WantedBy=default.target
  notify: Start Uptime Kuma Systemd unit file
