---
- name: Install podman
  become: true
  ansible.builtin.dnf:
    name: podman
    state: present
- name: Create Uptime Kuma quadlet file
  containers.podman.podman_container:
    name: uptime-kuma
    image: docker.io/louislam/uptime-kuma:1
    state: quadlet
    quadlet_filename: uptime-kuma
    quadlet_dir: "{{ ansible_user_dir }}/.config/containers/systemd"
    ports:
      - 3001:3001
    volumes:
      - "uptime-kuma:/app/data:z"
    quadlet_options:
      - "AutoUpdate=registry"
      - |
        [Service]
        Restart=always
        [Install]
        WantedBy=default.target
  notify: Start Uptime Kuma Systemd unit file
