---
- name: Enable Nginx
  ansible.builtin.systemd_service:
    name: nginx
    enabled: true
- name: Restart Nginx
  ansible.builtin.systemd_service:
    name: nginx
    state: restarted
- name: Restorecon
  ansible.builtin.command: restorecon -v /var/www
