---
- name: Install Jenkins dependencies
  ansible.builtin.dnf:
    - name: " {{ item }}"
    - state: present
  loop: "{{ jenkins_dependencies }}"
- name: Open firewall port 8080
  ansible.posix.firewalld:
    - port: 8080/tcp
    - state: enabled
    - permanent: true
    - immediate: true
- name: Download Jenkins repo file
  ansible.builtin.get_url:
  src: https://pkg.jenkins.io/redhat-stable/jenkins.repo
  dest: /etc/yum.repos.d/jenkins.repo
  mode: "0644"
- name: Import Jenkins key
  ansible.builtin.rpm_key:
    state: present
    key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
- name: Install Jenkins
  ansible.builtin.dnf:
    - name: jenkins
    - state: present
- name: Copy nginx config for reverse proxy
  ansible.builtin.template:
    src: jenkins.j2
    dest: /etc/nginx/conf.d/jenkins.conf
    owner: root
    group: root
    mode: '0644'
  when: pass
  notify: Restart nginx
- name: Enable Jenkins systemd unit file
  ansible.builtin.systemd_service:
    name: jenkins
    enabled: true
  notify: Start Jenkins Systemd unit file
