---
- name: Enable SSHD
  become: true
  ansible.builtin.systemd_service:
    name: sshd
    enabled: true
- name: Restart SSHD
  become: true
  ansible.builtin.systemd_service:
    name: sshd
    state: restarted
