---
ca_smallstep_url: "https://packages.smallstep.com/stable/fedora/"
ca_smallstep_gpg: "https://packages.smallstep.com/keys/smallstep-0x889B19391F774443.gpg"
ca_smallstep_packages:
  - step-cli
  - step-ca
ca_smallstep_password_file: "/etc/step-ca/password.txt"
ca_smallstep_password: "{{ vault_ca_smallstep_password }}"
ca_smallstep_initial_directory: "/root/.step"
ca_smallstep_global_directory: "/etc/step-ca"
