---
- name: Enable Alloy
  ansible.builtin.systemd_service:
    name: alloy
    enabled: true
    state: started
- name: Restart Alloy
  ansible.builtin.systemd_service:
    name: alloy
    state: restarted
