---
- name: Install podman
  become: true
  ansible.builtin.dnf:
    name: podman
    state: present
- name: Create Kavita quadlet file
  containers.podman.podman_container:
    name: kavita
    image: docker.io/linuxserver/kavita:latest
    state: quadlet
    quadlet_filename: kavita
    quadlet_dir: "{{ ansible_user_dir }}/.config/containers/systemd/"
    ports:
      - 5000:5000
    volumes:
      - "{{ ansible_user_dir }}/kavita_config:/config:z"
      - "{{ ansible_user_dir }}/books_for_kavita:/data:z"
    quadlet_options:
      - "AutoUpdate=registry"
      - "Environment=PUID=1000 PGID=1000 TZ=America/Los_Angeles"
      - |
        [Service]
        Restart=always
        [Install]
        WantedBy=default.target
  notify: Start Systemd unit file
