---
- name: Enable Rysyslog
  become: true
  ansible.builtin.systemd_service:
    name: rysslog
    enabled: true
    state: started
- name: Restart Rsyslog
  become: true
  ansible.builtin.systemd_service:
    name: rsyslog
    state: restarted
