---
- name: Install FreeIPA Server
  ansible.builtin.dnf:
    name: ipa-server
    state: present
- name: Set FQDN hostname
  ansible.builtin.hostname:
    name: "{{ freeipa_fqdn }}"
    use: systemd
- name: Set /etc/hosts to include DNS resolution for FQDN
  ansible.builtin.template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: '0644'
- name: Open required ports on firewalld
  ansible.posix.firewalld:
    service: "{{ item }}"
    state: enabled
    permanent: true
    immediate: true
  loop: "{{ freeipa_services }}"
- name: Set default login shell to bash
  community.general.ipa_config:
    ipadefaultloginshell: /usr/bin/bash
    ipa_host: "{{ freeipa_fqdn }}"
    ipa_user: "{{ freeipa_admin }}"
    ipa_pass: "{{ vault_freeipa_admin_password }}"
- name: Create mbc user
  community.general.ipa_user:
    name: "{{ freeipa_username }}"
    state: present
    givenname: Matt
    sn: Cohen
    loginshell: /usr/bin/bash
    password: "{{ freeipa_user_password }}"
    update_password: on_create
    ipa_host: "{{ freeipa_fqdn }}"
    ipa_user: "{{ freeipa_admin }}"
    ipa_pass: "{{ vault_freeipa_admin_password }}"
