---
- name: Install Podman
  block:
    - name: Install necessary packages
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      loop: "{{ forgejo_packages }}"

    - name: Enable podman auto-update service
      ansible.builtin.systemd_service:
        name: podman-auto-update.timer
        enabled: true
        state: started

- name: Set up forgejo
  become: true
  notify: Restart forgejo
  block:
    - name: Pull forgejo image
      containers.podman.podman_image:
        name: "{{ forgejo_image }}"
        tag: latest

    - name: Create forgejo podman volume
      containers.podman.podman_volume:
        name: forgejo-data
        state: present

    - name: Create forgejo network
      containers.podman.podman_network:
        name: forgejo

    - name: Create forgejo quadlet file
      containers.podman.podman_container:
        name: forgejo
        image: "{{ forgejo_image }}"
        state: quadlet
        quadlet_filename: forgejo
        quadlet_dir: /etc/containers/systemd
        network: forgejo
        volume:
          - forgejo-data:/data:z
        publish:
          - 3000:3000
          - 222:22
        env:
          USER_UID: 1000
          USER_GUID: 1000
        quadlet_options:
          - "AutoUpdate=registry"
          - |
            [Unit]
            Wants=network-online.target
            After=network-online.target
            [Service]
            Restart=always
            [Install]
            WantedBy=default.target

- name: Start forgejo
  become: true
  ansible.builtin.systemd_service:
    name: forgejo
    daemon_reload: true
    state: started

- name: Add forgejo custom firewalld service
  ansible.builtin.copy:
    src: forgejo.xml
    dest: /etc/firewalld/services/forgejo.xml
    owner: root
    group: root
    mode: "0644"
  notify: Restart firewalld

- name: Add forgejo firewalld service
  ansible.posix.firewalld:
    service: forgejo
    permanent: true
    immediate: true
    state: enabled
