---
- name: Make OpenBao data directory
  ansible.builtin.file:
    path: "{{ openbao_data_dir }}"
    state: directory
    owner: openbao
    group: openbao
    mode: "0775"

- name: Download OpenBao package
  ansible.builtin.get_url:
    url: "https://github.com/openbao/openbao/releases/download/v{{ openbao_version }}/bao_{{ openbao_version }}_linux_amd64.rpm"
    dest: "{{ openbao_pkg_path }}"
    owner: root
    group: root
    mode: "0644"

- name: Import OpenBao GPG key
  ansible.builtin.rpm_key:
    state: present
    key: "{{ openbao_gpg_key }}"

- name: Install OpenBao
  ansible.builtin.dnf:
    name: "{{ openbao_pkg_path }}"
    state: present

- name: Copy OpenBao config
  ansible.builtin.template:
    src: openbao.hcl.j2
    dest: /etc/openbao/openbao.hcl
    owner: root
    group: root
    mode: "0664"

- name: Enable and start OpenBao service
  become: true
  ansible.builtin.systemd_service:
    name: openbao
    state: started
    enabled: true
    daemon_reload: true
