---
- name: Install Podman
  block:
    - name: Install Podman
      become: true
      ansible.builtin.dnf:
        name: podman
        state: present
    - name: Enable podman auto-update service
      ansible.builtin.systemd_service:
        name: podman-auto-update.timer
        enabled: true
        state: started

- name: Make OpenBao directory
  ansible.builtin.file:
    path: /opt/openbao/config
    state: directory
    owner: semaphore
    group: semaphore
    mode: "0775"

# - name: Open up OpenBao port (temp for testing, before caddy)
#   ansible.posix.firewalld:
#     port: 8200/tcp
#     state: enabled
#     permanent: true
#     immediate: true

- name: Install OpenBao
  become: true
  become_user: semaphore
  containers.podman.podman_container:
    name: openbao
    hostname: openbao
    image: docker.io/openbao/openbao-ubi
    volumes:
      - /opt/openbao/config:/openbao/config:z
    publish:
      - 8200:8200
    state: quadlet
    quadlet_filename: openbao
    quadlet_dir: "/home/semaphore/.config/containers/systemd/"
    quadlet_options:
      - "AutoUpdate=registry"
      - |
        [Service]
        Restart=always
        [Install]
        WantedBy=default.target
  notify: Restart openbao

- name: Enable and start openbao service
  become: true
  become_user: "{{ service_user }}"
  ansible.builtin.systemd_service:
    name: openbao
    state: started
    enabled: true
    scope: user
    daemon_reload: true
