---
- name: Install Podman
  block:
    - name: Install Podman
      become: true
      ansible.builtin.dnf:
        name: podman
        state: present
    - name: Enable linger (for podman containers)
      become: true
      become_user: "{{ service_user }}"
      ansible.builtin.command: loginctl enable-linger
      changed_when: false
    - name: Enable podman auto-update service
      ansible.builtin.systemd_service:
        name: podman-auto-update.timer
        enabled: true
        state: started

- name: Install OpenBao
  become: true
  become_user: semaphore
  containers.podman.podman_container:
    name: openbao
    hostname: openbao
    image: docker.io/openbao/openbao-ubi
    publish:
      - 8200:8200
    state: quadlet
    quadlet_filename: openbao
    quadlet_dir: "/home/semaphore/.config/containers/systemd/"
    quadlet_options:
      - "AutoUpdate=registry"
      - |
        [Service]
        Restart=always
        [Install]
        WantedBy=default.target
  notify: Restart openbao

- name: Enable and start openbao service
  become: true
  become_user: "{{ service_user }}"
  ansible.builtin.systemd_service:
    name: openbao
    state: started
    enabled: true
    scope: user
