---
- name: Install podman
  become: true
  ansible.builtin.dnf:
    name: podman
    state: present
- name: Create gerbera config directory
  become: true
  ansible.builtin.file:
    name: /opt/gerbera
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"
- name: Create Gerbera quadlet file
  containers.podman.podman_container:
    name: gerbera
    image: docker.io/gerbera/gerbera:latest
    state: quadlet
    quadlet_filename: gerbera
    quadlet_dir: "{{ ansible_user_dir }}/.config/containers/systemd"
    network:
      - host
    volumes:
      - "/opt/gerbera:/var/run/gerbera"
      - "/media/external/dlna:/mnt/content:ro"
    quadlet_options:
      - "AutoUpdate=registry"
      - |
        [Service]
        Restart=always
        [Unit]
        After=network-online.target
        [Install]
        WantedBy=default.target
  notify: Start Gerbera Systemd unit file
