---
- name: Enable PHP FPM
  become: true
  ansible.builtin.systemd_service:
    name: php-fpm
    enabled: true
- name: Restart nginx
  become: true
  ansible.builtin.systemd_service:
    name: nginx
    state: restarted
