---
- name: Install FreeIPA client
  ansible.builtin.dnf:
    name: freeipa-client
    state: present
- name: Remind user to run freeipa command
  ansible.builtin.debug:
    msg: "Please run `sudo ipa-client-install --mkhomedir`!"
- name: Set hostname to be FQDN
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}.{{ domain }}"
    use: systemd
  when: inventory_hostname != "freeipa"
- name: Copy MBC SSH key
  ansible.posix.authorized_key:
    state: present
    user: "{{ freeipa_username }}"
    key: "{{ lookup('file', '/home/mbc/.ssh/id_ed25519.pub') }}"
- name: Allow FreeIPA user in sudoers
  community.general.sudoers:
    name: "{{ freeipa_username }}"
    state: present
    user: "{{ freeipa_username }}"
    commands: ALL
    host: ALL
    nopassword: false
