---
- name: Install FreeIPA client
  ansible.builtin.dnf:
    name: freeipa-client
    state: present
- name: Remind user to run freeipa command
  ansible.builtin.debug:
    msg: "Please run `sudo ipa-client-install --mkhomedir`!"
- name: Set hostname to be FQDN
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}.{{ domain }}"
    use: systemd
  when: inventory_hostname != "freeipa"
- name: Check if FreeIPA user exists
  ansible.builtin.user:
    name: mbc
  check_mode: true
  register: user_check
- name: Bind to FreeIPA domain
  become: true
  ansible.builtin.expect:
    command: ipa-client-install --mkhomedir
    timeout: 600
    responses:
      "Provide the domain name of your IPA server":
        - "{{ freeipa_client_domain }}"
      "Provide your IPA server name":
        - "{{ freeipa_client_fqdn }}"
      "Proceed with fixed values and no DNS discovery":
        - "yes" # this is to disable dns auto discovery
      "Do you want to configure chrony with NTP server or pool address":
        - "no" # this is for chrony
      "Continue to configure the system with these values":
        - "yes" # confirms config
      "User authorized to enroll computers":
        - "{{ freeipa_client_admin_account }}"
      "Password for":
        - "{{ vault_freeipa_admin_password }}"
  no_log: false
  when: user_check.state is not defined
- name: Allow FreeIPA user in sudoers
  community.general.sudoers:
    name: "{{ freeipa_username }}"
    state: present
    user: "{{ freeipa_username }}"
    commands: ALL
    host: ALL
    nopassword: false
- name: Copy MBC SSH key
  ansible.posix.authorized_key:
    state: present
    user: "{{ freeipa_username }}"
    key: "{{ lookup('file', '/home/mbc/.ssh/id_ed25519.pub') }}"
